### ISSUE TITLE
How to use output from GitHub Action with `--output`?

### ISSUE THREAD

**Issue by MPV** [GoogleContainerTools/container-diff#410]
### Expected behavior

I'd like to be able to run the GitHub Action for `container-diff` using the `--output` flag, so I can pass/use the output from the command in other

### Actual behavior

Using the action (as in the steps below) triggers:
```
container-diff diff daemon://my.domain/my/repo:latest daemon://my.domain/my/repo:3401858ca10b2df5cbdb4341b75e4b9051e89722 --type=file  --output="container-diff-file.txt
```
...which gives:
```
cat: container-diff-file.txt: No such file or directory
Error: Process completed with exit code 1.
```

### Information

- container-diff version: `v0.17.0` (https://github.com/GoogleContainerTools/container-diff/commit/0695621c48497a11a893a8fc0af7965c674123da)
- Operating system: Linux (via GitHub Actions)

### Steps to reproduce the behavior

1. Run the GitHub Action for container-diff with the `--output` flag, as per below:

For example:
```yaml
      - name: Run container-diff analyze
        if: github.event_name == 'pull_request'
        uses: GoogleContainerTools/container-diff/actions@0695621c48497a11a893a8fc0af7965c674123da
        with:
          command: analyze          
          args: daemon://${{ env.IMAGE }}:${{ github.sha }} --output="container-diff-analyze.txt"

      - name: Publish container-diff analyze
        run: |
          echo '## `container-diff analyze`' > "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"
          cat container-diff-analyze.txt >> "${GITHUB_STEP_SUMMARY}"
          echo '```' >> "${GITHUB_STEP_SUMMARY}"
```

...or...

```yaml
      - name: Pull latest for comparison
        if: github.event_name == 'pull_request'
        run: docker pull ${{ env.IMAGE }}:latest

      - name: Run container-diff diff file
        if: github.event_name == 'pull_request'
        uses: GoogleContainerTools/container-diff/actions@0695621c48497a11a893a8fc0af7965c674123da
        with:
          command: diff          
          args: daemon://${{ env.IMAGE }}:latest daemon://${{ env.IMAGE }}:${{ github.sha }} --type=file  --output="container-diff-file.txt"
```

### Other info/context

Back in this PR:
- https://github.com/GoogleContainerTools/container-diff/pull/402

...we added a `Dockerfile` for running `container-diff`, which may be a contributing factor to the problem and hiding the complexity/errors of using `container-diff` like this. It could also just be that I'm not yet understanding what's causing the issue just yet, happy to learn why this kind of issue might occur.

**Comment by MPV** [comment]
I'm trying variants of this, but I haven't yet succeeded.

For example by trying to write to a file in `${GITHUB_WORKSPACE}`, I just get:

```yaml
      - name: Run container-diff analyze
        if: github.event_name == 'pull_request'
        uses: GoogleContainerTools/container-diff/actions@0695621c48497a11a893a8fc0af7965c674123da
        with:
          command: analyze          
          args: daemon://${{ env.IMAGE }}:${{ github.sha }} --output="${GITHUB_WORKSPACE}/container-diff-analyze.txt"
```

```
container-diff diff daemon://my.domain/my/repo:latest daemon://my.domain/my/repo:3401858ca10b2df5cbdb4341b75e4b9051e89722 --type=file  --output="${GITHUB_WORKSPACE}/container-diff-analyze.txt"
time="2023-12-15T09:53:30Z" level=error msg="invalid argument"
time="2023-12-[15](https://github.com/my.org/my-repo/actions/runs/7220505570/job/19673561383#step:14:16)T09:53:30Z" level=error msg="invalid argument"
```
